//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public int PlantId { get; set; }
        public string PlantName { get; set; }
        public string plantIrrigationInstructions { get; set; }
        public string plantPlace { get; set; }
        public Nullable<int> plantPrice { get; set; }
        public string PlantImgSourceName { get; set; }
    }
}
